In [1]:
import numpy as np
import pandas as pd
from io import StringIO

In [2]:
a=[0,1,0,0,1]
b=[1,1,1,1,1]
c=[1,0,0,1,1]
d=[0,0,0,0,0]
e=[0,1,0,1,0]
ar=np.array([a,b,c,d,e])
df=pd.DataFrame(ar,index=['R1','R2','R3','R4','R5'],columns=['C1','C2','C3','C4','C5'])
df.to_csv("/Volumes/MACAir (A)/JUPYTER PROJECTS/PYTHON_JUPYTER/FILES_JUPYTER/binary_df.csv",index=False)

In [3]:
ar.shape

(5, 5)

In [4]:
bin_csv=pd.read_csv("FILES_JUPYTER/binary_df.csv")
bin_csv

   C1  C2  C3  C4  C5
0   0   1   0   0   1
1   1   1   1   1   1
2   1   0   0   1   1
3   0   0   0   0   0
4   0   1   0   1   0

In [5]:
data=('a,b,c,d\n'
      '1,2,3,4\n'
      '5,6,7,8\n'
      '9,10,11,12')
data_csv=pd.read_csv(StringIO(data))
data_csv

   a   b   c   d
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [6]:
sep_csv=pd.read_csv("FILES_JUPYTER/sep.txt", sep=r'\s+')

~"sep=r'\s+'" is a special expression which tells pandas to treat any cluster of spaces as a column divider.
                        
~It is better than "sep='\t'" because it can separate both tabs and blank spaces and, perfectly aligns columns

In [7]:
sep_csv

    name  class  marks
0  abdul      4     36
1   ramu      7     54
2  rekha      9     71
3  shyam      8     50
4  vinay      5     15
5  sunil     10     70

In [8]:
bin_csv

   C1  C2  C3  C4  C5
0   0   1   0   0   1
1   1   1   1   1   1
2   1   0   0   1   1
3   0   0   0   0   0
4   0   1   0   1   0

In [9]:
data_csv

   a   b   c   d
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [10]:
data_col=pd.read_csv(StringIO(data),usecols=['a'])
print(data_col)    #column name(s) must be inputed in form of a list

   a
0  1
1  5
2  9

=> sep_csv is present in a text file:- sep.txt    
=> bin_csv is present in a csv file:- binary_df.csv   
=> data_csv is made in this notebook having a variable named "data"

In [11]:
bin_nan=pd.read_csv("FILES_JUPYTER/binary_df.csv",na_values=[0])
print(bin_nan)

    C1   C2   C3   C4   C5
0  NaN  1.0  NaN  NaN  1.0
1  1.0  1.0  1.0  1.0  1.0
2  1.0  NaN  NaN  1.0  1.0
3  NaN  NaN  NaN  NaN  NaN
4  NaN  1.0  NaN  1.0  NaN

In [12]:
bin_csv

   C1  C2  C3  C4  C5
0   0   1   0   0   1
1   1   1   1   1   1
2   1   0   0   1   1
3   0   0   0   0   0
4   0   1   0   1   0

In [17]:
bin_header=pd.read_csv("FILES_JUPYTER/binary_df.csv",header=2)
bin_header

   1  1.1  1.2  1.3  1.4
0  1    0    0    1    1
1  0    0    0    0    0
2  0    1    0    1    0

In [14]:
StringIO(data)

In [20]:
data_csv

   a   b   c   d
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [24]:
pd.read_csv(StringIO(data),index_col=[0,3])

       b   c
a d
1 4    2   3
5 8    6   7
9 12  10  11

In [25]:
sep_csv

    name  class  marks
0  abdul      4     36
1   ramu      7     54
2  rekha      9     71
3  shyam      8     50
4  vinay      5     15
5  sunil     10     70

=> the columns used in index_col must also be included in usecols otherwise it will throw a value error

In [41]:
sep2=pd.read_csv("FILES_JUPYTER/sep.txt", sep=r'\s+',usecols=["name","class","marks"],index_col="name")
sep2

       class  marks
name
abdul      4     36
ramu       7     54
rekha      9     71
shyam      8     50
vinay      5     15
sunil     10     70

In [42]:
sep2.loc["vinay"]

class     5
marks    15
Name: vinay, dtype: int64