In [1]:
import numpy as np
import pandas as pd
from io import StringIO

In [2]:
dat=('index,a,b,c\n'
     '4,apple,bat,5.7\n'
     '8,orange,cow,10')
pd.read_csv(StringIO(dat))

   index       a    b     c
0      4   apple  bat   5.7
1      8  orange  cow  10.0

=> when 'b' and 'c' are included in the usecols, the column  indexes change because it is now viewed as a dataframe containing   only 2 columns:- b and c; **excluding 'index' and 'a'  columns.**   
     So, when the column index of 'b' and 'c' are 0 and 1 respectively.

In [10]:
pd.read_csv(StringIO(dat),usecols=['b','c'],index_col=0)

        c
b
bat   5.7
cow  10.0