~ Create a DataFrame that takes cell number as row and animal name and population as columns

In [18]:
import numpy as np
import pandas as pd
import ast

In [19]:
cell=int(input("Enter no of cells:-"))
#columns are fixed:- "name", "population","male","female"
l=[]
print("For no input in population, enter 'nan' or 'NaN'")
for i in range(0,cell):
    anm_inp=input("Enter name of the animal:-")
    if anm_inp=="":     # if I don't enter any animal
        anm=np.nan
        row=[anm,0,0,0]
        l.append(row)
    else:
        anm=anm_inp
        pop_inp=int(input("Enter population of the animal:-"))
        if pop_inp==0:      # if no animal of that type exists
            row=[anm,0,0,0]
            l.append(row)
        else:
            male=int(input("Enter male animals:-"))
            female=int(input("Enter female animals:-"))
            row=[anm,pop_inp,male,female]
            l.append(row)
        '''if pop_inp!={'nan','NaN'}:
            print("For no input in male or female animals, enter 'nan' or 'NaN'")
            male=float(input("Enter male animals:-"))
            female=float(input("Enter female animals:-"))
            row=[anm,pop_inp,male,female]
            l.append(row)
        else:
            pop=pop_inp
            row=[anm,0,0,0]
            l.append(row)'''
print(l)

ValueError: invalid literal for int() with base 10: ''

~ If I input a animal name, then surely it will have a population. If i input nothing in animal's name, then no need for inserting the population.

~ Since I can't do math with null value, so no need to put NaN in population, male and female column. Keeping these column's input integer type (because we don't need float now).

In [ ]:
df=pd.DataFrame(l,index=range(1,cell+1),columns=["Name","Population","Male","Female"])

In [ ]:
df

       Name  Population  Male  Female
1      lion           4     2       2
2     tiger           5     2       3
3  elephant          10     4       5
4       NaN           0     0       0

In [ ]:
df["Male"].value_counts()

Male
2    2
4    1
0    1
Name: count, dtype: int64

In [ ]:
print("types of animal present in the zoo:-",df["Name"].nunique()) #didn't count NaN, that's good

types of animal present in the zoo:- 3

In [ ]:
df.loc[4,["Name","Population","Male","Female"]]=["monkey",5,1,4]
#replacing data present in the dataframe

In [22]:
df

       Name  Population  Male  Female
1      lion           4     2       2
2     tiger           5     2       3
3  elephant          10     4       5
4    monkey           5     1       4

In [23]:
df.fillna(3)

       Name  Population  Male  Female
1      lion           4     2       2
2     tiger           5     2       3
3  elephant          10     4       5
4    monkey           5     1       4

In [27]:
mn=df["Population"].mean()
print(mn,type(mn))      #output type is float

6.0 <class 'numpy.float64'>