~ Creating a attendance sheet of a school having 3 sections:A,B,C   
~ Each section will have some students and they will be marked **present or absent**.

In [1]:
import pandas as pd
import numpy as np
from io import StringIO

In [2]:
#First we need to create a dataframe.
'''Blueprint:-
    sections:- A,B,C
        A:-John, Adam, Rick
        B:-Bill, Jane, Kenny
        C:-Walton, Isabel, Lili'''

'Blueprint:-\n    sections:- A,B,C\n        A:-John, Adam, Rick\n        B:-Bill, Jane, Kenny\n        C:-Walton, Isabel, Lili'

In [3]:
# This one is for dataframe
st_dict={"A":["John","Adam","Rick"],
         "B":["Bill","Jane","Kenny"],
         "C":["Walton","Isabel","Lili"]
        }

~~ While using a dictionary to create a dataframe, the keys become the column names while   the values are the elements of the respective key-columns.

In [4]:
stdf=pd.DataFrame(st_dict)
stdf

      A      B       C
0  John   Bill  Walton
1  Adam   Jane  Isabel
2  Rick  Kenny    Lili

In [5]:
stdf.to_json("FILES_JUPYTER/STUDENTS.JSON",indent=4)
stdf.to_json()

'{"A":{"0":"John","1":"Adam","2":"Rick"},"B":{"0":"Bill","1":"Jane","2":"Kenny"},"C":{"0":"Walton","1":"Isabel","2":"Lili"}}'

In [6]:
att_dt=[{"Section":"A",
        "students":["John","Adam","Rick"],
        "attendance":
                [{"John":"Present"},
                 {"Adam":"Absent"},
                 {"Rick":"Absent"}
                 ]},
        {"Section":"B",
        "students":["Bill","Jane","Kenny"],
        "attendance":
                [{"Bill":"Present"},
                 {"Jane":"Absent"},
                 {"Kenny":"Present"}
                 ]},
        {"Section":"C",
        "students":["Walton","Isabel","Lili"],
        "attendance":
                [{"Walton":"Present"},
                 {"Isabel":"Absent"},
                 {"Lili":"Present"}
                 ]}
        ]
# att_dt is in json format

In [7]:
att_df=pd.DataFrame(att_dt)
att_df

,Section,students,attendance
0,A,"[John, Adam, Rick]","[{'John': 'Present'}, {'Adam': 'Absent'}, {'Ri..."
1,B,"[Bill, Jane, Kenny]","[{'Bill': 'Present'}, {'Jane': 'Absent'}, {'Ke..."
2,C,"[Walton, Isabel, Lili]","[{'Walton': 'Present'}, {'Isabel': 'Absent'}, ..."

In [8]:
att_j=att_df.to_json("FILES_JUPYTER/attendace.json",indent=4)

In [9]:
att_df.to_json()

'{"Section":{"0":"A","1":"B","2":"C"},"students":{"0":["John","Adam","Rick"],"1":["Bill","Jane","Kenny"],"2":["Walton","Isabel","Lili"]},"attendance":{"0":[{"John":"Present"},{"Adam":"Absent"},{"Rick":"Absent"}],"1":[{"Bill":"Present"},{"Jane":"Absent"},{"Kenny":"Present"}],"2":[{"Walton":"Present"},{"Isabel":"Absent"},{"Lili":"Present"}]}}'

#### Let's create another json data on the book:- "Deep work"

In [10]:
'''Blueprint:-
    book:- Deep Work
    author:- Cal Newport
    details:-
        pages:- 304,
        cover type:- Paperback,
        ISBN:- 9781455586691'''

'Blueprint:-\n    book:- Deep Work\n    author:- Cal Newport\n    details:-\n        pages:- 304,\n        cover type:- Paperback,\n        ISBN:- 9781455586691'

In [11]:
book_dat={"Book":"Deep Work",
          "Author":"Cal Newport",
          "Details":[{"pages":304,
                      "cover type":"Papertype",
                      "ISBN":9781455586691}
                    ]
        }
book_df=pd.DataFrame(book_dat)
book_df

        Book       Author                                            Details
0  Deep Work  Cal Newport  {'pages': 304, 'cover type': 'Papertype', 'ISB...

=> Now we have 3 json datas in this demojson.pynb.   
=> st_dict and att_dt had been saved in form of json files named
    "attendance.json" and "STUDENTS.JSON" respectively.  
=> book_dat is present in form of a dataframe and in json format.

In [12]:
book_df.to_json("FILES_JUPYTER/Deep Work.json",indent=4)

In [13]:
pd.read_json("FILES_JUPYTER/STUDENTS.JSON")

      A      B       C
0  John   Bill  Walton
1  Adam   Jane  Isabel
2  Rick  Kenny    Lili

In [14]:
pd.read_json("FILES_JUPYTER/STUDENTS.JSON",orient="records")

      A      B       C
0  John   Bill  Walton
1  Adam   Jane  Isabel
2  Rick  Kenny    Lili

In [15]:
pd.read_json("FILES_JUPYTER/ST2.json",orient="split")

      A      B       C
0  John   Bill  Walton
1  Adam   Jane  Isabel
2  Rick  Kenny    Lili

=> orient="split", explicitly looks for a dictionary that contains 3 specific keys: "columns", "index", and "data".     
=> ST2.json is a json file which has the same values present in STUDENTS.JSON but in form of the above mentioned way.

In [16]:
pd.read_json("FILES_JUPYTER/Deep Work.json",orient="columns")

        Book       Author                                            Details
0  Deep Work  Cal Newport  {'pages': 304, 'cover type': 'Papertype', 'ISB...

In [17]:
print(pd.read_json("FILES_JUPYTER/Deep Work.json"))

        Book       Author                                            Details
0  Deep Work  Cal Newport  {'pages': 304, 'cover type': 'Papertype', 'ISB...

=> object="columns" is the default.

In [18]:
pd.read_json("FILES_JUPYTER/Deep Work.json",orient="index")

                                                         0
Book                                             Deep Work
Author                                         Cal Newport
Details  {'pages': 304, 'cover type': 'Papertype', 'ISB...

In [19]:
'''pd.read_json(".vscode/settings.json")
        DON'T RUN THIS CODE'''

'pd.read_json(".vscode/settings.json")\n        DON\'T RUN THIS CODE'

In [20]:
stdf.to_json(orient="records")

'[{"A":"John","B":"Bill","C":"Walton"},{"A":"Adam","B":"Jane","C":"Isabel"},{"A":"Rick","B":"Kenny","C":"Lili"}]'

In [21]:
stdf.to_json()

'{"A":{"0":"John","1":"Adam","2":"Rick"},"B":{"0":"Bill","1":"Jane","2":"Kenny"},"C":{"0":"Walton","1":"Isabel","2":"Lili"}}'

In [22]:
stdf

      A      B       C
0  John   Bill  Walton
1  Adam   Jane  Isabel
2  Rick  Kenny    Lili

In [23]:
stdf.to_json(orient="index")

'{"0":{"A":"John","B":"Bill","C":"Walton"},"1":{"A":"Adam","B":"Jane","C":"Isabel"},"2":{"A":"Rick","B":"Kenny","C":"Lili"}}'

In [24]:
stdf.to_json(orient="values")

'[["John","Bill","Walton"],["Adam","Jane","Isabel"],["Rick","Kenny","Lili"]]'

In [25]:
book_df.to_json(orient="table")

'{"schema":{"fields":[{"name":"index","type":"integer"},{"name":"Book","type":"string"},{"name":"Author","type":"string"},{"name":"Details","type":"string"}],"primaryKey":["index"],"pandas_version":"1.4.0"},"data":[{"index":0,"Book":"Deep Work","Author":"Cal Newport","Details":{"pages":304,"cover type":"Papertype","ISBN":9781455586691}}]}'

In [26]:
sch='{"schema":{"fields":[{"name":"index","type":"integer"},{"name":"Book","type":"string"},{"name":"Author","type":"string"},{"name":"Details","type":"string"}],"primaryKey":["index"],"pandas_version":"1.4.0"},"data":[{"index":0,"Book":"Deep Work","Author":"Cal Newport","Details":{"pages":304,"cover type":"Papertype","ISBN":9781455586691}}]}'

In [27]:
pd.read_json(StringIO(sch),orient="table")

        Book       Author                                            Details
0  Deep Work  Cal Newport  {'pages': 304, 'cover type': 'Papertype', 'ISB...

In [28]:
pd.json_normalize(book_dat)

        Book       Author                                            Details
0  Deep Work  Cal Newport  [{'pages': 304, 'cover type': 'Papertype', 'IS...

In [29]:
book_dat

{'Book': 'Deep Work',
 'Author': 'Cal Newport',
 'Details': [{'pages': 304, 'cover type': 'Papertype', 'ISBN': 9781455586691}]}

In [30]:
pd.json_normalize(book_dat,meta=["Book","Author"],record_path="Details")

   pages cover type           ISBN       Book       Author
0    304  Papertype  9781455586691  Deep Work  Cal Newport

In [31]:
pd.json_normalize(st_dict)

                    A                    B                       C
0  [John, Adam, Rick]  [Bill, Jane, Kenny]  [Walton, Isabel, Lili]

In [32]:
st_dict

{'A': ['John', 'Adam', 'Rick'],
 'B': ['Bill', 'Jane', 'Kenny'],
 'C': ['Walton', 'Isabel', 'Lili']}