~ First, we will create xml files and then we will use them.

In [1]:
import numpy as np
import pandas as pd
from io import StringIO

In [2]:
job_data={"ID":[17,59,35,29,40],
          "Name":["Jack","Anne","Peter","Daniel","Jovile"],
          "Profession":["Doctor","Mechanic","Manager","Engineer",
                        "Teacher"]}
df=pd.DataFrame(job_data)
df.to_xml("FILES_JUPYTER/jobs.xml",index=False)

In [3]:
job_att=df.to_xml(index=False,attr_cols=["ID","Name","Profession"])
# This is not permanently saved

In [4]:
print(job_att)

<?xml version='1.0' encoding='utf-8'?>
<data>
  <row ID="17" Name="Jack" Profession="Doctor"/>
  <row ID="59" Name="Anne" Profession="Mechanic"/>
  <row ID="35" Name="Peter" Profession="Manager"/>
  <row ID="29" Name="Daniel" Profession="Engineer"/>
  <row ID="40" Name="Jovile" Profession="Teacher"/>
</data>

In [5]:
pd.read_xml(StringIO(job_att),xpath="./*")      #DEFAULT
pd.read_xml(StringIO(job_att),xpath=".//row")   # NO CHANGE
pd.read_xml(StringIO(job_att))                  #DEFAULT

   ID    Name Profession
0  17    Jack     Doctor
1  59    Anne   Mechanic
2  35   Peter    Manager
3  29  Daniel   Engineer
4  40  Jovile    Teacher

In [6]:
pd.read_xml("FILES_JUPYTER/jobs.xml",elems_only=True)
# "FILES_JUPYTER/jobs.xml" doesn't have any value in container attributes.
# It is in element-centric format.

   ID    Name Profession
0  17    Jack     Doctor
1  59    Anne   Mechanic
2  35   Peter    Manager
3  29  Daniel   Engineer
4  40  Jovile    Teacher

In [7]:
pd.read_xml(StringIO(job_att),attrs_only=True)
# job_att does have any child elements in text tags.
# It is in attribute-centric format

   ID    Name Profession
0  17    Jack     Doctor
1  59    Anne   Mechanic
2  35   Peter    Manager
3  29  Daniel   Engineer
4  40  Jovile    Teacher