# PANDAS HTML DEMO

In [1]:
import numpy as np
import pandas as pd
from io import StringIO

In [2]:
html=pd.read_html("https://www.boldtuesday.com/pages/alphabetical-list-of-all-countries-and-capitals-shown-on-list-of-countries-poster?srsltid=AfmBOor6kFPabteXsFPr_uxBNuM44A3Ujv7IetVJZzQbY-UHGQz_k7Vn")
# table having list of countriea and its capital

HTTPError: HTTP Error 429: Too Many Requests

In [ ]:
html[1]

                       0                    1
0       B (17 countries)     B (17 countries)
1           BAHAMAS, THE               NASSAU
2                BAHRAIN               MANAMA
3             BANGLADESH                DHAKA
4               BARBADOS           BRIDGETOWN
5                BELARUS                MINSK
6                BELGIUM             BRUSSELS
7                 BELIZE             BELMOPAN
8                  BENIN           PORTO-NOVO
9                 BHUTAN              THIMPHU
10               BOLIVIA        SUCRE, LA PAZ
11  BOSNIA & HERZEGOVINA             SARAJEVO
12              BOTSWANA             GABORONE
13                BRAZIL             BRASILIA
14                BRUNEI  BANDAR SERI BEGAWAN
15              BULGARIA                SOFIA
16          BURKINA FASO          OUAGADOUGOU
17               BURUNDI    GITEGA, BUJUMBURA

In [ ]:
html2=pd.read_html("https://www.boldtuesday.com/pages/alphabetical-list-of-all-countries-and-capitals-shown-on-list-of-countries-poster?srsltid=AfmBOor6kFPabteXsFPr_uxBNuM44A3Ujv7IetVJZzQbY-UHGQz_k7Vn",match="INDIA",index_col=0)
print(html2)
# table containing contries starting with "I"

[                               1
0
I (8 countries)  I (8 countries)
ICELAND                REYKJAVIK
INDIA                  NEW DELHI
INDONESIA                JAKARTA
IRAN                      TEHRAN
IRAQ                     BAGHDAD
IRELAND                   DUBLIN
ISRAEL                 JERUSALEM
ITALY                       ROME]

In [ ]:
type(html2)

list

In [ ]:
html3=pd.read_html("https://afd.calpoly.edu/web/sample-tables")

In [ ]:
html3[-1]

,NAME OF SYSTEM OR PORTAL CHANNEL,NAME OF SYSTEM OR ACTIVITY,STATUS DURING OUTAGE,DATA FROZEN AS OF,EXPECTED UP TIME
0,Personal Information,Addresses,View Only,1/18/2008,Go live date
1,Personal Information,Names,View Only,1/18/2008,Go live date
2,Personal Information,Phone Numbers,View Only,1/18/2008,Go live date
3,Personal Information,Emergency Contacts,View Only,1/18/2008,Go live date
4,Group Leave Balance,Group Leave Balances,View Only,12/31/2007,3/1/2008
5,Leave/CTO Balances,Leave and CTO Balances,View Only,12/31/2007,3/1/2008
6,Faculty Course Info,Class Search/Browse Catalog,NaN,NaN,NaN
7,Faculty Course Info,Record Grades,NaN,NaN,NaN
8,Faculty Course Info,Access Class Roster,NaN,NaN,NaN
9,Faculty Course Info,Student Data,NaN,NaN,NaN
10,Faculty Course Info,View My Class Schedule,NaN,NaN,NaN
11,Faculty Course Info,View My Weekly Schedule,NaN,NaN,NaN
12,Enrollment Planning,View Course Catalog and Schedule of Classes,NaN,NaN,NaN
13,Student Pay,Timekeeper Access,Unavailable,1/18/2008,NaN
14,PolyData,????,NaN,NaN,NaN
15,PolyData,NaN,NaN,NaN,NaN
16,PolyProfile,NaN,NaN,NaN,NaN
17,PolyProfile,NaN,NaN,NaN,NaN
18,PolyProfile,NaN,NaN,NaN,NaN

In [ ]:
id_data={"ID":[1023,1482,1738,1936,1007],
         "Name":["Jake","Steve","Kalie","Harry","Jenny"]}
id_df=pd.DataFrame(id_data)
id_df

     ID   Name
0  1023   Jake
1  1482  Steve
2  1738  Kalie
3  1936  Harry
4  1007  Jenny

In [ ]:
html4=id_df.to_html("FILES_JUPYTER/ID.html",index=False)

In [ ]:
print(pd.read_html("FILES_JUPYTER/ID.html",index_col="ID"))
ID_rowdf=pd.read_html("FILES_JUPYTER/ID.html",index_col="ID")

[       Name
ID
1023   Jake
1482  Steve
1738  Kalie
1936  Harry
1007  Jenny]

In [ ]:
print(type(ID_rowdf))

<class 'list'>

In [ ]:
'''html4_1=id_df.to_html("FILES_JUPYTER/ID.html",index=False,justify="center")
print(pd.read_html("FILES_JUPYTER/ID.html",index_col="ID"))
# HTML text has been aligned to center'''

'html4_1=id_df.to_html("FILES_JUPYTER/ID.html",index=False,justify="center")\nprint(pd.read_html("FILES_JUPYTER/ID.html",index_col="ID"))\n# HTML text has been aligned to center'

In [ ]:
html5=pd.read_html("https://en.wikipedia.org/wiki/The_Conjuring_Universe")

HTTPError: HTTP Error 403: Forbidden