## USING PANDAS ##

In [2]:
import pandas as pd
import numpy as np

In [3]:
l1=["SRIBASCHHA","ECE",9]
l2=["Ram","CSE",8.4]
l3=["SUMAN","Civil",8]
dat=np.array([l1,l2,l3])
print(dat)

[['SRIBASCHHA' 'ECE' '9']
 ['Ram' 'CSE' '8.4']
 ['SUMAN' 'Civil' '8']]

In [4]:
la=[2,3,4,5]
lb=[4,7,9,1]
lc=[1,5,3,8]
dat2=np.array([la,lb,lc])
print(dat2)

[[2 3 4 5]
 [4 7 9 1]
 [1 5 3 8]]

In [5]:
df2=pd.DataFrame(dat2,index=['R1','R2','R3'],columns=['COL1','COL2','COL3','COL4'])

In [6]:
df1=pd.DataFrame(dat,index=[1,2,3],columns=["Name","Branch","CGPA"])

In [7]:
df1.head()

         Name Branch CGPA
1  SRIBASCHHA    ECE    9
2         Ram    CSE  8.4
3       SUMAN  Civil    8

In [8]:
df2.head()

    COL1  COL2  COL3  COL4
R1     2     3     4     5
R2     4     7     9     1
R3     1     5     3     8

In [9]:
print(type(df2))

<class 'pandas.core.frame.DataFrame'>

In [10]:
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 1 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Branch  3 non-null      object
 2   CGPA    3 non-null      object
dtypes: object(3)
memory usage: 96.0+ bytes
None

In [11]:
print(df2.info())

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, R1 to R3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   COL1    3 non-null      int64
 1   COL2    3 non-null      int64
 2   COL3    3 non-null      int64
 3   COL4    3 non-null      int64
dtypes: int64(4)
memory usage: 120.0+ bytes
None

In [12]:
print(df1.head())
print(df1.describe())

         Name Branch CGPA
1  SRIBASCHHA    ECE    9
2         Ram    CSE  8.4
3       SUMAN  Civil    8
              Name Branch CGPA
count            3      3    3
unique           3      3    3
top     SRIBASCHHA    ECE    9
freq             1      1    1

In [13]:
print(df2.head())
print(df2.describe())

    COL1  COL2  COL3  COL4
R1     2     3     4     5
R2     4     7     9     1
R3     1     5     3     8
           COL1  COL2      COL3      COL4
count  3.000000   3.0  3.000000  3.000000
mean   2.333333   5.0  5.333333  4.666667
std    1.527525   2.0  3.214550  3.511885
min    1.000000   3.0  3.000000  1.000000
25%    1.500000   4.0  3.500000  3.000000
50%    2.000000   5.0  4.000000  5.000000
75%    3.000000   6.0  6.500000  6.500000
max    4.000000   7.0  9.000000  8.000000

In [14]:
'''df1=df1.drop(4)                     # DON'T RUN THIS CELL #
#df1=df1.drop([0,1,2],axis=1)
print(df1)'''

"df1=df1.drop(4)                     # DON'T RUN THIS CELL #\n#df1=df1.drop([0,1,2],axis=1)\nprint(df1)"

In [15]:
l4 = ["Danish", "Mech", 7.5]                    #ADDING NEW ROW
new1 = pd.DataFrame([l4], columns=["Name", "Branch", "CGPA"], index=[4])
df1 = pd.concat([df1, new1])
print(df1)

         Name Branch CGPA
1  SRIBASCHHA    ECE    9
2         Ram    CSE  8.4
3       SUMAN  Civil    8
4      Danish   Mech  7.5

In [16]:
'''df1=df1.drop([5,6,7])            # DON'T RUN THIS CELL #
df1=df1.drop([0,1,2],axis=1)
print(df1)'''
#df1=df1.drop(4)

"df1=df1.drop([5,6,7])            # DON'T RUN THIS CELL #\ndf1=df1.drop([0,1,2],axis=1)\nprint(df1)"

In [17]:
df1

         Name Branch CGPA
1  SRIBASCHHA    ECE    9
2         Ram    CSE  8.4
3       SUMAN  Civil    8
4      Danish   Mech  7.5

In [18]:
l5=["Amit","IT",9]
l6=["SHYAM","CSE",np.nan]
l7=[np.nan]                 #it takes 'Name' and 'CGPA' as NaN, but 'Branch' as None
#name as NaN because first element in l7 is np.nan.
#branch as None because python's pandas default value is None under a object/ text type data column.
#CGPA as NaN because elements under that column is of float data type.
new2=pd.DataFrame([l5,l6,l7],index=[5,6,7],columns=["Name", "Branch", "CGPA"])
df1=pd.concat([df1,new2])
print(df1)

         Name Branch CGPA
1  SRIBASCHHA    ECE    9
2         Ram    CSE  8.4
3       SUMAN  Civil    8
4      Danish   Mech  7.5
5        Amit     IT  9.0
6       SHYAM    CSE  NaN
7         NaN   None  NaN

In [19]:
df1

         Name Branch CGPA
1  SRIBASCHHA    ECE    9
2         Ram    CSE  8.4
3       SUMAN  Civil    8
4      Danish   Mech  7.5
5        Amit     IT  9.0
6       SHYAM    CSE  NaN
7         NaN   None  NaN

In [20]:
df2

    COL1  COL2  COL3  COL4
R1     2     3     4     5
R2     4     7     9     1
R3     1     5     3     8

In [21]:
ld=[5,7,6,2]
le=[9,0,1,4]
lf=[8,5,3,0]
lg=[np.nan]
newa=pd.DataFrame([ld,le,lf,lg],index=['R4','R5','R6','R7'],columns=['COL1','COL2','COL3','COL4'])
df2=pd.concat([df2,newa])
print(df2)

    COL1  COL2  COL3  COL4
R1   2.0   3.0   4.0   5.0
R2   4.0   7.0   9.0   1.0
R3   1.0   5.0   3.0   8.0
R4   5.0   7.0   6.0   2.0
R5   9.0   0.0   1.0   4.0
R6   8.0   5.0   3.0   0.0
R7   NaN   NaN   NaN   NaN

In [22]:
lh=[0,3,np.nan,5]
ar=np.array([lh])
newb=pd.DataFrame(ar,index=["R8"],columns=['COL1','COL2','COL3','COL4'])
df2=pd.concat([df2,newb])
print(df2)

    COL1  COL2  COL3  COL4
R1   2.0   3.0   4.0   5.0
R2   4.0   7.0   9.0   1.0
R3   1.0   5.0   3.0   8.0
R4   5.0   7.0   6.0   2.0
R5   9.0   0.0   1.0   4.0
R6   8.0   5.0   3.0   0.0
R7   NaN   NaN   NaN   NaN
R8   0.0   3.0   NaN   5.0

In [23]:
print(df2.info())
print("-"*70)
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, R1 to R8
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   COL1    7 non-null      float64
 1   COL2    7 non-null      float64
 2   COL3    6 non-null      float64
 3   COL4    7 non-null      float64
dtypes: float64(4)
memory usage: 320.0+ bytes
None
----------------------------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, 1 to 7
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Branch  6 non-null      object
 2   CGPA    5 non-null      object
dtypes: object(3)
memory usage: 224.0+ bytes
None

In [24]:
print(df2.describe())
print("-"*70)
print(df1.describe())

           COL1      COL2      COL3      COL4
count  7.000000  7.000000  6.000000  7.000000
mean   4.142857  4.285714  4.333333  3.571429
std    3.436499  2.497618  2.804758  2.760262
min    0.000000  0.000000  1.000000  0.000000
25%    1.500000  3.000000  3.000000  1.500000
50%    4.000000  5.000000  3.500000  4.000000
75%    6.500000  6.000000  5.500000  5.000000
max    9.000000  7.000000  9.000000  8.000000
----------------------------------------------------------------------
              Name Branch CGPA
count            6      6    5
unique           6      5    5
top     SRIBASCHHA    CSE    9
freq             1      2    1

In [25]:
print(df2)
print("-"*70)
print(df1)

    COL1  COL2  COL3  COL4
R1   2.0   3.0   4.0   5.0
R2   4.0   7.0   9.0   1.0
R3   1.0   5.0   3.0   8.0
R4   5.0   7.0   6.0   2.0
R5   9.0   0.0   1.0   4.0
R6   8.0   5.0   3.0   0.0
R7   NaN   NaN   NaN   NaN
R8   0.0   3.0   NaN   5.0
----------------------------------------------------------------------
         Name Branch CGPA
1  SRIBASCHHA    ECE    9
2         Ram    CSE  8.4
3       SUMAN  Civil    8
4      Danish   Mech  7.5
5        Amit     IT  9.0
6       SHYAM    CSE  NaN
7         NaN   None  NaN

In [26]:
print(type(df2[["COL3","COL2"]]))
df2[["COL3","COL1"]]

<class 'pandas.core.frame.DataFrame'>

    COL3  COL1
R1   4.0   2.0
R2   9.0   4.0
R3   3.0   1.0
R4   6.0   5.0
R5   1.0   9.0
R6   3.0   8.0
R7   NaN   NaN
R8   NaN   0.0

In [46]:
print(type(df2["COL2"]))        # 1-D part of the dataframe, so series
df2["COL2"]

<class 'pandas.core.series.Series'>

R1    3.0
R2    7.0
R3    5.0
R4    7.0
R5    0.0
R6    5.0
R7    NaN
R8    3.0
Name: COL2, dtype: float64

In [28]:
print(df2.loc[['R8',"R3"]])
print("_"*50)
print(df1.loc[[4,6]])

    COL1  COL2  COL3  COL4
R8   0.0   3.0   NaN   5.0
R3   1.0   5.0   3.0   8.0
__________________________________________________
     Name Branch CGPA
4  Danish   Mech  7.5
6   SHYAM    CSE  NaN

In [29]:
df2

    COL1  COL2  COL3  COL4
R1   2.0   3.0   4.0   5.0
R2   4.0   7.0   9.0   1.0
R3   1.0   5.0   3.0   8.0
R4   5.0   7.0   6.0   2.0
R5   9.0   0.0   1.0   4.0
R6   8.0   5.0   3.0   0.0
R7   NaN   NaN   NaN   NaN
R8   0.0   3.0   NaN   5.0

In [30]:
print(df2.iloc[0:5:2,0::3].values)
print(df2.iloc[0:5:2,0::3])

[[2. 5.]
 [1. 8.]
 [9. 4.]]
    COL1  COL4
R1   2.0   5.0
R3   1.0   8.0
R5   9.0   4.0

In [31]:
df1

         Name Branch CGPA
1  SRIBASCHHA    ECE    9
2         Ram    CSE  8.4
3       SUMAN  Civil    8
4      Danish   Mech  7.5
5        Amit     IT  9.0
6       SHYAM    CSE  NaN
7         NaN   None  NaN

In [32]:
print(df1.iloc[4:,0:].values)

[['Amit' 'IT' 9.0]
 ['SHYAM' 'CSE' nan]
 [nan None nan]]

In [33]:
df1.isnull().sum()==0

Name      False
Branch    False
CGPA      False
dtype: bool

In [34]:
df2

    COL1  COL2  COL3  COL4
R1   2.0   3.0   4.0   5.0
R2   4.0   7.0   9.0   1.0
R3   1.0   5.0   3.0   8.0
R4   5.0   7.0   6.0   2.0
R5   9.0   0.0   1.0   4.0
R6   8.0   5.0   3.0   0.0
R7   NaN   NaN   NaN   NaN
R8   0.0   3.0   NaN   5.0

In [35]:
print(df2["COL3"].value_counts())

COL3
3.0    2
4.0    1
9.0    1
6.0    1
1.0    1
Name: count, dtype: int64

In [36]:
df2[df2["COL3"]>4]

    COL1  COL2  COL3  COL4
R2   4.0   7.0   9.0   1.0
R4   5.0   7.0   6.0   2.0

In [37]:
# Show rows where COL3 > 4 AND COL4 > 4
df2[(df2['COL3'] > 4) & (df2['COL4'] > 4)]

Empty DataFrame
Columns: [COL1, COL2, COL3, COL4]
Index: []

In [38]:
df2[(df2['COL3'] > 4) | (df2['COL4'] > 4)]

    COL1  COL2  COL3  COL4
R1   2.0   3.0   4.0   5.0
R2   4.0   7.0   9.0   1.0
R3   1.0   5.0   3.0   8.0
R4   5.0   7.0   6.0   2.0
R8   0.0   3.0   NaN   5.0

In [39]:
df2.isnull().sum()

COL1    1
COL2    1
COL3    2
COL4    1
dtype: int64

In [40]:
df1["Branch"].value_counts()

Branch
CSE      2
ECE      1
Civil    1
Mech     1
IT       1
Name: count, dtype: int64

In [41]:
df2

    COL1  COL2  COL3  COL4
R1   2.0   3.0   4.0   5.0
R2   4.0   7.0   9.0   1.0
R3   1.0   5.0   3.0   8.0
R4   5.0   7.0   6.0   2.0
R5   9.0   0.0   1.0   4.0
R6   8.0   5.0   3.0   0.0
R7   NaN   NaN   NaN   NaN
R8   0.0   3.0   NaN   5.0

In [42]:
print(type(df2["COL2"].unique()))
print(df2.nunique())

<class 'numpy.ndarray'>
COL1    7
COL2    4
COL3    5
COL4    6
dtype: int64

In [43]:
df1

         Name Branch CGPA
1  SRIBASCHHA    ECE    9
2         Ram    CSE  8.4
3       SUMAN  Civil    8
4      Danish   Mech  7.5
5        Amit     IT  9.0
6       SHYAM    CSE  NaN
7         NaN   None  NaN

In [44]:
df1["Name"].value_counts(normalize=True)*100           #gives percentage of each element of that column

Name
SRIBASCHHA    16.666667
Ram           16.666667
SUMAN         16.666667
Danish        16.666667
Amit          16.666667
SHYAM         16.666667
Name: proportion, dtype: float64

In [45]:
print(df1["Name"].value_counts(dropna=False))   #It counts the occurences of nan value
print(df1["Name"].value_counts())               # default function does not count null value

Name
SRIBASCHHA    1
Ram           1
SUMAN         1
Danish        1
Amit          1
SHYAM         1
NaN           1
Name: count, dtype: int64
Name
SRIBASCHHA    1
Ram           1
SUMAN         1
Danish        1
Amit          1
SHYAM         1
Name: count, dtype: int64